server:
  port: 7800
spring:
  application:
    name: consumer-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO

hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 5000 # 设置hystrix的超时时间为6000ms:
#feign集成hystrix必须开启
feign:
  hystrix:
    enabled: true